### ISSUE TITLE
Body HTML is rendered in live preview but not in MAIL itself

### ISSUE THREAD

**Issue by gauranshkumar** [gauranshkumar/chithi#9]
This is a small bug where the text actually sent to the MAIL Body is not the HTML but rather the text itself, so all we need to do is instead of sending the direct text from the textbox we need to parse the markdown and send the HTML to the body, this can be achieved via `body = markdown.markdown(body)`

**Comment by charmainessseah** [comment]
Hey I'm new to open source. I'd like to take this issue!

**Comment by gauranshkumar** [comment]
Hey @charmainessseah Sure I am assigning this to you, please feel free to ask any doubts if you have any.
